#!/bin/bash



if [[ $OSTYPE == 'darwin'* ]]; then
  echo 'downloading ' & \
  curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64  && \

echo 'configuring' && mv tailwindcss-macos-arm64 tailwindcss && \

echo 'finalizing '  && chmod +x tailwindcss
else
echo 'downloading ' & \
curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64   && \

echo 'configuring' && mv  tailwindcss-linux-x64  tailwindcss && \

echo 'finalizing '  && chmod +x tailwindcss

fi
